service: slack-bot-for-task-rotation
frameworkVersion: "2 || 3"

custom:
  tableName: "rotations-${sls:stage}"
  dynamodb:
    # Accepted stages must be whitelisted for DynamoDB Local
    stages:
      - staging
      - development
    start:
      port: 8000
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: "rotations-${sls:stage}"
            sources: [./seed/rotations.json]
  stages:
    - development
    - staging
    - production

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-stage-manager

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [RotationsTable, Arn]
  environment:
    ROTATIONS_TABLE: ${self:custom.tableName}
    IS_OFFLINE: true

functions:
  createRotation:
    handler: handlers/create-rotations.handler
    events:
      - http:
          path: slack/events
          method: post

  listRotations:
    handler: handlers/list-rotations.handler
    events:
      - http:
          path: slack/events/rotations/list
          method: post

  deleteRotation:
    handler: handlers/delete-rotation.handler
    events:
      - http:
          path: slack/events/rotations/delete
          method: post

  executeRotation:
    handler: handlers/execute-rotations.handler
    events:
      - schedule: cron(0 12 ? * MON-FRI *)

resources:
  Resources:
    RotationsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: next_rotation_at
            AttributeType: S
          - AttributeName: channel_id
            AttributeType: S
          - AttributeName: task
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: next_rotation_at
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: "ByChannelId"
            KeySchema:
              - AttributeName: "channel_id"
                KeyType: "HASH"
              - AttributeName: "task"
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
